version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=taskai_dev
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=taskai_dev
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: